### This is a task to install tomcat
--- 
- hosts: all
  name: Installing Apache-tomcat
  become: yes
  tasks: 
    - name: Installing tomcat package
      yum:
        name: tomcat 
        state: present
  
    - name: Verifying Lynx Installation
      yum:
        name: lynx
        state: present
